# **Prediction script for the models**

In [1]:
# imports

import torch
import pandas as pd
import tqdm
import numpy as np
from models.YouTubeDataset import YouTubeDataset
from models.ClipBertViewPredictor import ClipBertViewPredictor

/users/eleves-a/2023/baptiste.arnaudo/Predict-YouTube-Views/venv/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/users/eleves-a/2023/baptiste.arnaudo/Predict-YouTube-Views/venv/lib64/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
test_set = pd.read_csv('./dataset/processed_test_set.csv', sep=';')
test_set

,id,title,description,sin_month,cos_month,sin_dayofmonth,cos_dayofmonth,sin_hour,cos_hour,sin_dayofweek,...,channel_category_UCW6NyJ6oFLPTnx7iGRZXDDg,channel_category_UCWnTC8o8AycL6a2eRrKSdBg,channel_category_UCX894EiI3iOKez6ULmZFlOg,channel_category_UCXLfJIEp91L-fD0gP131IaQ,channel_category_UCiCnPY--pbn5S8JkJdV2PbQ,channel_category_UCkE6ZzUxUY_XMP688ib-RWA,channel_category_UCpJ6Dn01AqjvFVN2EiK72Ag,channel_category_UCpUhcwq3oB7HKvrNeQmxJsg,channel_category_UCrSvhrtUgpZT3EU0x1Zoy-w,channel_category_UCyp-EzJrdTOd9uNPvmdst-w
0,0,নিজের অতীত ভুলে গেলে #bengalimovies #banglacin...,Enjoy and stay connected with us!!\n\nSubscrib...,-2.449294e-16,1.000000e+00,-0.651372,-0.758758,7.071068e-01,7.071068e-01,0.433884,...,0,0,0,0,1,0,0,0,0,0
1,1,2024: A YEAR IN FILMS,"Here we are, at the end of another cinematic y...",-5.000000e-01,8.660254e-01,-0.937752,0.347305,-9.659258e-01,-2.588190e-01,0.000000,...,0,0,0,0,0,0,0,0,0,0
2,2,Short film on Argentina's military dictatorshi...,"Argentina, on 1983. A woman dedicates her whol...",-1.000000e+00,-1.836970e-16,-0.897805,-0.440394,-2.588190e-01,-9.659258e-01,-0.974928,...,1,0,0,0,0,0,0,0,0,0
3,3,Rupantar | রূপান্তর - Full Movie | Sabyasachi ...,"Watch the Bengali Full Movie ""Rupantar"" Starri...",-8.660254e-01,5.000000e-01,-0.485302,-0.874347,1.224647e-16,-1.000000e+00,-0.433884,...,0,0,0,0,1,0,0,0,0,0
4,4,ALEPPO | Omeleto Drama,A doctor suffers a brain injury.\n\n\nALEPPO i...,-5.000000e-01,-8.660254e-01,-0.724793,0.688967,8.660254e-01,5.000000e-01,-0.974928,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3397,3397,VISKAR I VINDEN | Omeleto Comedy,A man investigates a murder.\n\n\nVISKAR I VIN...,5.000000e-01,8.660254e-01,-0.988468,0.151428,1.000000e+00,6.123234e-17,0.974928,...,0,0,0,0,0,0,0,0,0,0
3398,3398,THE SESSION | Omeleto Drama,A musician is chained to a piano.\n\n\nTHE SES...,5.000000e-01,8.660254e-01,-0.485302,-0.874347,1.000000e+00,6.123234e-17,0.433884,...,0,0,0,0,0,0,0,0,0,0
3399,3399,REVENGE OF THE ELECTRIC CART | Omeleto Drama,A young girl overcome prejudice.\n\n\nREVENGE ...,8.660254e-01,5.000000e-01,0.897805,-0.440394,9.659258e-01,2.588190e-01,-0.974928,...,0,0,0,0,0,0,0,0,0,0
3400,3400,LIKENESS | Omeleto,A young woman investigates her mother's disapp...,8.660254e-01,5.000000e-01,-0.848644,0.528964,9.659258e-01,2.588190e-01,0.000000,...,0,0,0,0,0,0,0,0,0,0
3401,3401,FACE TO FACE | Omeleto Drama,A reporter confronts an online troll.\n\n\nFAC...,5.000000e-01,8.660254e-01,-0.651372,-0.758758,9.659258e-01,-2.588190e-01,-0.433884,...,0,0,0,0,0,0,0,0,0,0

In [4]:
nb_nan_desc = test_set['description'].isna().sum()
nb_nan_desc # Problem !

np.int64(620)

In [3]:
test_set['description'].fillna('', inplace=True)
test_set['description'].isna().sum() # No more nan

/tmp/ipykernel_1148512/1572416197.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_set['description'].fillna('', inplace=True)

np.int64(0)

In [4]:
test_set.isna().sum()

id                                           0
title                                        0
description                                  0
sin_month                                    0
cos_month                                    0
sin_dayofmonth                               0
cos_dayofmonth                               0
sin_hour                                     0
cos_hour                                     0
sin_dayofweek                                0
cos_dayofweek                                0
sin_dayofyear                                0
cos_dayofyear                                0
channel_category_UC-1rx8j9Ggp8mp4uD0ZdEIA    0
channel_category_UC-vrN89jIox3XqAKbEMeFgQ    0
channel_category_UC6P24bhhCmMPOcujA9PKPTA    0
channel_category_UC71x8bBOwIEscxAltguHXMQ    0
channel_category_UC7sDT8jZ76VLV1u__krUutA    0
channel_category_UCHUnLXalwe66kBndfmH5cXA    0
channel_category_UCMOB6uDg7e-h8OuCw8dK2_Q    0
channel_category_UCTMt7iMWa7jy0fNXIktwyLA    0
channel_category_UCTWiOA2IQyW_QaGv4t2UaCQ    0
channel_category_UCVNNriW_Mc2prgngYZ69T0A    0
channel_category_UCW6NyJ6oFLPTnx7iGRZXDDg    0
channel_category_UCWnTC8o8AycL6a2eRrKSdBg    0
channel_category_UCX894EiI3iOKez6ULmZFlOg    0
channel_category_UCXLfJIEp91L-fD0gP131IaQ    0
channel_category_UCiCnPY--pbn5S8JkJdV2PbQ    0
channel_category_UCkE6ZzUxUY_XMP688ib-RWA    0
channel_category_UCpJ6Dn01AqjvFVN2EiK72Ag    0
channel_category_UCpUhcwq3oB7HKvrNeQmxJsg    0
channel_category_UCrSvhrtUgpZT3EU0x1Zoy-w    0
channel_category_UCyp-EzJrdTOd9uNPvmdst-w    0
dtype: int64

In [14]:
import os
missing = [i for i in test_set["id"] if not os.path.exists(f"./dataset/test/{i}.jpg")]
print(f"{len(missing)} thumbnails missing out of {len(test_set)}")

0 thumbnails missing out of 3402

In [7]:
train_set = pd.read_csv('./dataset/processed_training_set.csv', sep=';')
train_set

,id,title,description,logviews,sin_month,cos_month,sin_dayofmonth,cos_dayofmonth,sin_hour,cos_hour,...,channel_category_UCW6NyJ6oFLPTnx7iGRZXDDg,channel_category_UCWnTC8o8AycL6a2eRrKSdBg,channel_category_UCX894EiI3iOKez6ULmZFlOg,channel_category_UCXLfJIEp91L-fD0gP131IaQ,channel_category_UCiCnPY--pbn5S8JkJdV2PbQ,channel_category_UCkE6ZzUxUY_XMP688ib-RWA,channel_category_UCpJ6Dn01AqjvFVN2EiK72Ag,channel_category_UCpUhcwq3oB7HKvrNeQmxJsg,channel_category_UCrSvhrtUgpZT3EU0x1Zoy-w,channel_category_UCyp-EzJrdTOd9uNPvmdst-w
0,draLUXVFLzM,"CGI 3D Sci-Fi Animated Short: ""AO"" | By Cristi...","TheCGBros Presents the Sci-Fi Short Film: ""AO""...",10.746584,-5.000000e-01,-8.660254e-01,-0.968077,-0.250653,-0.866025,-0.500000,...,0,0,0,0,0,0,0,0,0,0
1,rer1ohR6TcY,Oshadharon | Bengali Audio Story | Bibhutibhus...,"Presenting the Bengali Audio Story ""Oshadharon...",8.593599,5.000000e-01,8.660254e-01,-0.571268,0.820763,0.965926,-0.258819,...,0,0,0,0,1,0,0,0,0,0
2,6CSODwvm4E8,Crunchy (A Micro-Horror Film),Every good cereal comes with a fun toy! Every ...,7.370860,1.224647e-16,-1.000000e+00,-0.998717,-0.050649,0.965926,-0.258819,...,0,0,0,0,0,0,0,0,0,0
3,vWbfQAWSIj4,"CGI 3D Animated Short: ""Astrosinge"" - by Astro...",Watch this hilarious 3D animated short called ...,10.602343,8.660254e-01,-5.000000e-01,0.101168,-0.994869,0.965926,0.258819,...,0,0,0,0,0,0,0,0,0,0
4,_rJongrpMv8,Mondays: Writers Block & Making An Animated Mo...,Today Ryan answers questions about writers blo...,10.590768,8.660254e-01,-5.000000e-01,0.299363,-0.954139,-0.258819,0.965926,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12380,Hxbv__KVfFo,"CGI Animated Short Film: ""Meli Metro"" by ESMA ...",CGI 3D Animated Short Film: Meli Metro Animate...,12.553234,5.000000e-01,8.660254e-01,-0.790776,-0.612106,-0.707107,0.707107,...,0,0,0,0,0,0,0,0,1,0
12381,pk-hw-crAF8,"CGI 3D Animated Short: ""The Promise"" - by Marc...","TheCGBros Presents ""The Promise"" by Marcos Tor...",9.523398,-1.000000e+00,-1.836970e-16,-0.651372,-0.758758,-0.866025,-0.500000,...,0,0,0,0,0,0,0,0,0,0
12382,q8hA7hyh9sk,"CGI & VFX Showreels: ""VFX Reel 2019"" - by Kons...",Check out this latest showreel from the talent...,10.018422,-5.000000e-01,-8.660254e-01,0.790776,-0.612106,0.866025,0.500000,...,0,0,0,0,0,0,0,0,0,0
12383,YqHymoDD_tQ,Sci-Fi Short Film “They Watch” | DUST,"In an alternate future, an idealistic teen fig...",12.445790,-5.000000e-01,8.660254e-01,0.848644,0.528964,-0.866025,-0.500000,...,0,0,0,0,0,0,0,0,0,0
12384,86H5S0poQik,"""Paranormal Solutions Inc."" Episode 5 & 6 Horr...",Subscribe to ALTER on YouTube: https://goo.gl/...,10.702705,8.660254e-01,5.000000e-01,-0.651372,-0.758758,-0.500000,-0.866025,...,0,0,0,0,0,0,0,0,0,0

In [5]:
def predict(model, dataset, params_path):
    """
    Predict the labels of the test set using the trained model.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    print(f"Using device: {device}")
    # Load the model
    model = model.to(device)
    model.load_state_dict(torch.load(params_path, map_location=device))
    model.eval()

    def collate_fn(batch):
        return {
            "image": [x["image"] for x in batch],
            "title": [x["title"] for x in batch],
            "description": [x["description"] for x in batch],
            "tabular": torch.stack([x["tabular"] for x in batch]),
            "id": [x["id"] for x in batch]
        }

    test_loader = torch.utils.data.DataLoader(dataset, batch_size=128, shuffle=False, 
                                               collate_fn=collate_fn, num_workers=2)
    all_predictions = []
    all_ids = []

    with torch.no_grad():
        progress_bar = tqdm.tqdm(test_loader, desc="Validating", leave=False)
        for i, batch in enumerate(progress_bar):
            try:
                inputs = {
                "image": batch["image"],
                "title": batch["title"],
                "description": batch["description"],
                "tabular": batch["tabular"].to(device)
                }
                outputs = model(inputs)
                all_predictions.extend(torch.exp(outputs).cpu().numpy().flatten().tolist())
                all_ids.extend(batch["id"])

            except Exception as e:
                print(f"Error processing batch {i}: {e}")
                print(f"Batch keys: {list(batch.keys())}")
                for k, v in batch.items():
                    print(f"{k}: {type(v)}")
                continue
    
    # Create a DataFrame to store the predictions
    predictions_df = pd.DataFrame({
        "ID": all_ids,
        "predictions": all_predictions
    })
    predictions_df = predictions_df.sort_values('ID')

    # Save the predictions to a CSV file
    predictions_df.to_csv("predictions.csv", index=False)
    print("Predictions saved to predictions.csv")
    return predictions_df

In [15]:
dataset = YouTubeDataset("./dataset/processed_test_set.csv", "./dataset/test/", ratio=1, is_test=True)
model = ClipBertViewPredictor(frozen=True)
params_path = "./models/best_model_clipbertpredictor.pth"
prediction_df = predict(model, dataset, params_path)
prediction_df

Using device: cuda

Validating:   0%|          | 0/27 [00:00<?, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Predictions saved to predictions.csv

        ID    predictions
423      0    3565.066406
3176     1   15059.184570
2016     2    2747.147217
2461     3   75935.125000
2953     4    5768.149902
...    ...            ...
748   3397    7339.043457
1965  3398   18703.177734
1748  3399   10227.620117
281   3400  642007.062500
1739  3401    7082.026855

[3402 rows x 2 columns]

In [6]:
# test to see if the predictions work

dataset = YouTubeDataset("./dataset/processed_validation_set.csv", "./dataset/train_val", ratio=1, is_test=True)
model = ClipBertViewPredictor()
params_path = "./models/best_model_clipbertpredictor.pth"
prediction_df = predict(model, dataset, params_path)

val_set = pd.read_csv('./dataset/processed_validation_set.csv', sep=';')

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

Using device: cuda

Predictions saved to predictions.csv

In [9]:
# Compute the accuracy of the predictions on the validation set (should be arount 2.0)

def custom_loss_function(prediction_df, val_set):
    """
    Custom loss function to compute the accuracy of the predictions.
    """
    merged = val_set.merge(prediction_df, left_on='id', right_on='ID', how='inner')
    true_views = np.exp(merged['logviews'].values)
    pred_views = merged['predictions'].values
    msle = np.mean((np.log1p(true_views) - np.log1p(pred_views))**2)
    return msle

custom_loss_function(prediction_df, val_set)

np.float64(2.660743748788803)